const demoPortfolio={"id": "sample", "name": "Sample portfolio", "createdAt": "2026-01-01T00:00:00.000Z", "status": "demo", "summary": {"positions": 5, "marketValue": 100000, "unrealizedGain": 5000, "unrealizedGainPct": 5.26, "topThreeWeight": 75, "topSixWeight": 100, "decisionReadiness": "sample_only", "researchConfidence": 0}, "positions": [["DEMOA", "Example Software", 30, 12, "review", "Research pending", ["na", "na", "na"]], ["DEMOB", "Example Bank", 25, 6, "review", "Research pending", ["na", "na", "na"]], ["DEMOC", "Example Consumer", 20, -4, "review", "Research pending", ["na", "na", "na"]], ["DEMOD", "Example Energy", 15, 2, "review", "Research pending", ["na", "na", "na"]], ["DEMOE", "Example Healthcare", 10, 3, "review", "Research pending", ["na", "na", "na"]]], "dataQuality": {"holdings": {"score": 0}, "charts": {"score": 0}, "fundamentals": {"score": 0}, "valuation": {"score": 0}}, "allocation": {"groups": [{"label": "Sample holdings", "detail": "Fictional data", "weightPct": 100, "color": "#27765a"}]}};
let positions=demoPortfolio.positions;
let portfolio=structuredClone(demoPortfolio);
const app=document.querySelector("#app"),modal=document.querySelector("#uploadModal"),settingsModal=document.querySelector("#settingsModal"),toast=document.querySelector("#toast");
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const notify=m=>{toast.textContent=m;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)};
const initials=name=>name.split(" ").slice(0,2).map(x=>x[0]).join("");
const displayName=name=>String(name||"Saved portfolio").replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const trend=t=>`<div class="trend" title="Monthly · Weekly · Daily">${t.map((x,i)=>`<i class="${x==='flat'?'':x}">${x==='up'?'↗':x==='down'?'↘':x==='na'?'–':'→'}</i>`).join("")}</div>`;
function donutGradient(groups){let cursor=0;const stops=groups.map(group=>{const start=cursor;cursor+=group.weightPct||0;return `${group.color||'#c9d4cd'} ${start}% ${cursor}%`});return groups.length?`conic-gradient(${stops.join(',')})`:"#edf0ec"}

function portfolioVisuals(){
  const totalWeight=positions.reduce((sum,p)=>sum+(p[2]||0),0)||100;
  const groups=[
    {key:"core",label:"Core / keep",color:"#27765a",rows:positions.filter(p=>["core","keep"].includes(p[4]))},
    {key:"review",label:"Review",color:"#d4a14d",rows:positions.filter(p=>p[4]==="review")},
    {key:"exit",label:"Exit review",color:"#c76a62",rows:positions.filter(p=>p[4]==="exit")},
    {key:"reconcile",label:"Reconcile",color:"#6d8792",rows:positions.filter(p=>p[4]==="reconcile")}
  ].map(g=>({...g,weight:g.rows.reduce((sum,p)=>sum+(p[2]||0),0)}));
  const contributors=positions.filter(p=>Number.isFinite(p[3])).map(p=>({...p,contribution:p[2]*p[3]/100})).sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution)).slice(0,7);
  const max=Math.max(...contributors.map(p=>Math.abs(p.contribution)),1);
  const winners=positions.filter(p=>Number.isFinite(p[3])&&p[3]>0).length,losers=positions.filter(p=>Number.isFinite(p[3])&&p[3]<0).length,exceptions=positions.filter(p=>p[3]===null).length;
  const pending=!portfolio.horizons||portfolio.summary?.researchConfidence===0;
  const priorityItems=(portfolio.priorities||[]).slice(0,4);
  const actionMarkup=pending?`<div class="action-item warning"><span class="action-number">1</span><div><h3>Complete evidence processing</h3><p>The portfolio is saved, but charts, fundamentals and valuation evidence must be attached before actions can be ranked.</p></div><span class="pill reconcile">Required</span></div>`:priorityItems.length?priorityItems.map(item=>`<div class="action-item ${item.type==='reconcile'?'danger':item.type==='sizing_review'?'warning':''}"><span class="action-number">${item.rank}</span><div><h3>${item.title}</h3><p>${item.reason}</p></div><span class="pill ${item.type==='reconcile'?'reconcile':item.type==='sizing_review'?'review':'keep'}">${String(item.type).replaceAll('_',' ')}</span></div>`).join(""):`<div class="action-item warning"><span class="action-number">1</span><div><h3>Review missing evidence</h3><p>No ranked portfolio priorities were generated.</p></div><span class="pill reconcile">Required</span></div>`;
  return `<div class="section-divider"><h2>Decision analytics</h2></div><section class="visual-grid">
    <article class="visual-card"><div class="visual-card-head"><div><h2>Portfolio by research action</h2><p>How much capital sits in each decision bucket</p></div><div class="chart-legend">${groups.map(g=>`<span><i style="background:${g.color}"></i>${g.label}</span>`).join("")}</div></div><div class="stacked-chart" aria-label="Portfolio weight by research action">${groups.map(g=>`<i style="width:${g.weight/totalWeight*100}%;background:${g.color}" title="${g.label}: ${g.weight.toFixed(1)}%"></i>`).join("")}</div><div class="bucket-grid">${groups.map(g=>`<div class="bucket"><span>${g.label}</span><strong>${g.weight.toFixed(1)}%</strong><small>${g.rows.length} position${g.rows.length===1?'':'s'}</small></div>`).join("")}</div><div class="outcome-band"><div><strong class="positive">${winners}</strong><small>Profitable positions</small></div><div><strong class="negative">${losers}</strong><small>Loss positions</small></div><div><strong>${exceptions}</strong><small>Data exceptions</small></div></div></article>
    <article class="visual-card"><div class="visual-card-head"><div><h2>Return contribution signal</h2><p>Approximation using portfolio weight × recorded return</p></div></div><div class="contributor-chart">${contributors.length?contributors.map(p=>`<div class="contributor-row"><span>${p[1]}</span><div class="contributor-track"><i class="${p.contribution<0?'negative-bar':''}" style="width:${Math.max(3,Math.abs(p.contribution)/max*100)}%"></i></div><b class="${p.contribution>=0?'positive':'negative'}">${p.contribution>=0?'+':''}${p.contribution.toFixed(1)}pt</b></div>`).join(""):`<div class="empty">Return contribution becomes available after holdings are parsed.</div>`}</div><p class="chart-note">This identifies drivers of the recorded portfolio result; it does not prove business quality or predict future return.</p></article>
  </section><section class="visual-grid">
    <article class="visual-card"><div class="visual-card-head"><div><h2>What needs attention next</h2><p>Research actions, ordered before any execution decision</p></div><span class="pill ${pending?'reconcile':'review'}">${pending?'Analysis pending':`${priorityItems.length} priorities`}</span></div><div class="action-center">${actionMarkup}</div></article>
    <article class="visual-card"><div class="visual-card-head"><div><h2>Highest-attention positions</h2><p>Large weights and unresolved research states</p></div></div><div class="attention-list">${positions.slice().sort((a,b)=>b[2]-a[2]).filter(p=>!["core","keep"].includes(p[4])).slice(0,6).map(p=>`<div class="attention-row"><div><strong>${p[1]}</strong><small>${p[5]} · ${p[0]}</small></div><b>${p[2].toFixed(2)}%</b></div>`).join("")||`<div class="empty">No analyzed attention list yet.</div>`}</div><p class="chart-note">Position weight determines urgency; the label is a research queue, not an order instruction.</p></article>
  </section>`
}

function table(rows=positions){return `<div class="table-wrap"><table class="positions-table"><thead><tr><th>Company</th><th>Weight</th><th>Unrealized</th><th>M · W · D</th><th>Research view</th><th>Readiness</th></tr></thead><tbody>${rows.map(p=>`<tr><td><div class="company-cell"><span class="company-logo">${initials(p[1])}</span><div><strong>${p[1]}</strong><small>${p[0]} · NSE/BSE</small></div></div></td><td>${p[2].toFixed(2)}%</td><td class="${p[3]===null?'':p[3]>=0?'positive':'negative'}">${p[3]===null?'Needs reconciliation':`${p[3]>0?'+':''}${p[3].toFixed(2)}%`}</td><td>${trend(p[6])}</td><td><span class="pill ${p[4]}">${p[5]}</span></td><td>${["core","keep"].includes(p[4])?'Medium':p[4]==='reconcile'?'Blocked':'Low'}</td></tr>`).join("")}</tbody></table></div>`}

function dashboard(){const s=portfolio.summary||{};const q=portfolio.dataQuality||{};const horizons=portfolio.horizons||[];const allocation=portfolio.allocation?.groups||[];const horizonFallback=[{label:"Long term",title:"Analysis pending",summary:"Fundamental evidence has not been processed.",status:"unavailable"},{label:"Monthly",title:"Chart pending",summary:"Monthly evidence has not been processed.",status:"unavailable"},{label:"Weekly / daily",title:"Chart pending",summary:"Trend evidence has not been processed.",status:"unavailable"},{label:"Intraday",title:"Live data required",summary:"Fresh intraday evidence and risk limits are required.",status:"unavailable"}];return `<div class="page">
  <section class="hero-row"><div><span class="eyebrow">Portfolio intelligence</span><h1>See the risk behind the return.</h1><p>Public demo with fictional data. Explore the portfolio interface; private uploads and market connections are available in the local application.</p></div><div class="hero-actions"><button class="secondary-button" id="exportReport">Export report</button><button class="primary-button" id="runAnalysis">Run fresh analysis</button></div></section>
  <section class="metric-grid">
    <article class="metric primary"><span class="label">Portfolio value</span><strong>${money(s.marketValue||0)}</strong><small>${s.positions||positions.length} holdings · fictional sample</small><svg class="spark" viewBox="0 0 180 60"><path d="M0 53 C25 48 30 38 52 41 S83 26 102 31 S134 10 180 5" fill="none" stroke="#80c6a9" stroke-width="2"/><path d="M0 53 C25 48 30 38 52 41 S83 26 102 31 S134 10 180 5 V60 H0Z" fill="#2c6a55"/></svg></article>
    <article class="metric"><span class="label">Recorded gain</span><strong class="${(s.unrealizedGain||0)>=0?'positive':'negative'}">${s.unrealizedGain==null?'—':money(s.unrealizedGain)}</strong><small>${s.unrealizedGainPct==null?'Return pending':`${s.unrealizedGainPct>0?'+':''}${s.unrealizedGainPct.toFixed(2)}%`} · before data exceptions</small></article>
    <article class="metric"><span class="label">Concentration</span><strong>${s.topThreeWeight==null?'Pending':`${s.topThreeWeight.toFixed(2)}%`}</strong><small>Top 3 positions · review needed</small></article>
    <article class="metric"><span class="label">Decision readiness</span><strong>${String(s.decisionReadiness||"pending").replaceAll("_","–")}</strong><small>${portfolio.validation?.blockedCalculations?.length||0} calculations blocked by missing inputs</small></article>
  </section>
  <section class="dashboard-grid">
    <article class="card"><div class="card-head"><div><h2>Where your risk is concentrated</h2><p>Position concentration, not just sector labels</p></div><button class="link-button" data-go="positions">View positions →</button></div><div class="allocation"><div class="donut" style="background:${donutGradient(allocation)}"></div><div class="legend">${allocation.length?allocation.map(g=>`<div class="legend-row"><i style="background:${g.color}"></i><span>${g.label} · ${g.detail}</span><strong>${g.weightPct.toFixed(2)}%</strong></div>`).join(""):`<div class="legend-row"><span>Allocation analysis pending</span></div>`}</div></div></article>
    <article class="card"><div class="card-head"><div><h2>Research readiness</h2><p>Confidence in the research, not the investment</p></div></div><div class="readiness-score"><div class="score-ring" style="--score:${s.researchConfidence||0}"><div><strong>${s.researchConfidence||0}</strong><small>/ 100</small></div></div><div class="readiness-copy"><strong>${s.researchConfidence?'Useful, not execution-ready':'Analysis pending'}</strong><p>Holdings and chart evidence are shown separately from missing fundamental and valuation evidence.</p><span class="pill review">Evidence gated</span></div></div><div class="quality-list">${[["Holdings data",q.holdings?.score||0],["Chart coverage",q.charts?.score||0],["Fundamentals",q.fundamentals?.score||0],["Valuation",q.valuation?.score||0]].map(([label,value])=>`<div class="quality-row"><span>${label}</span><div class="mini-bar"><i style="width:${value}%"></i></div><b>${value}%</b></div>`).join("")}</div></article>
  </section>
  <section class="insight-grid">${(horizons.length?horizons:horizonFallback).map(h=>`<article class="insight"><span>${h.label}</span><h3>${h.title}</h3><p>${h.summary}</p><span class="pill ${h.status==='trend_visible'?'keep':h.status==='monitor'?'review':'reconcile'} status">${String(h.status||'pending').replaceAll('_',' ')}</span></article>`).join("")}</section>
  ${portfolioVisuals()}
  <section class="section-card" style="margin-top:17px"><div class="section-title"><div><h2>Priority positions</h2><p style="font-size:9px;color:var(--muted);margin:4px 0 0">Sorted by portfolio weight and decision urgency</p></div><div class="filters"><input class="search" id="positionSearch" placeholder="Search positions…"><select class="filter" id="viewFilter"><option value="">All views</option><option value="core">Core</option><option value="review">Review</option><option value="exit">Exit review</option><option value="reconcile">Reconcile</option></select></div></div><div id="positionsTable">${table(positions.slice(0,12))}</div></section>
  </div>`}

function positionsView(){return `<div class="page"><section class="hero-row"><div><span class="eyebrow">${positions.length} holdings</span><h1>Every position, one decision system.</h1><p>Outcome, weight, multi-timeframe trend and evidence readiness in one view.</p></div><button class="primary-button" id="uploadInline">＋ Add portfolio</button></section><section class="section-card"><div class="section-title"><h2>Complete portfolio</h2><div class="filters"><input class="search" id="positionSearch" placeholder="Search positions…"><select class="filter" id="viewFilter"><option value="">All views</option><option value="core">Core</option><option value="keep">Keep</option><option value="review">Review</option><option value="exit">Exit review</option><option value="reconcile">Reconcile</option></select></div></div><div id="positionsTable">${table()}</div></section></div>`}

function placeholder(view){const copy={analysis:["Four-horizon analysis","Compare long-term business evidence with monthly, weekly, daily and live intraday context."],monitor:["Thesis monitor","Track thesis breakers, position weights and evidence changes without rewriting history."],evidence:["Evidence room","Keep audited facts, external facts, management claims, inferences and projections visibly separate."],rules:["Your investment rules","Apply transparent rules without turning compatibility into a buy or sell recommendation."],journal:["Decision journal","Record what you knew, expected and risked before outcomes distort the memory."]}[view];return `<div class="page"><section class="empty-view"><span class="eyebrow">Research workspace</span><h1>${copy[0]}</h1><p>${copy[1]} This UI area is prepared for the next implementation phase.</p><button class="primary-button" data-go="portfolio">Return to portfolio</button></section></div>`}

function bind(){
  document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>location.hash=x.dataset.go);
  ["uploadInline"].forEach(id=>document.querySelector(`#${id}`)?.addEventListener("click",openModal));
  document.querySelector("#runAnalysis")?.addEventListener("click",()=>notify("This demo shows fictional holdings. Run the local research tools to evaluate evidence."));
  document.querySelector("#exportReport")?.addEventListener("click",()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(portfolio,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="sample-portfolio.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
  const search=document.querySelector("#positionSearch"),filter=document.querySelector("#viewFilter");
  const apply=()=>{let rows=positions;const q=(search?.value||"").toLowerCase(),f=filter?.value||"";if(q)rows=rows.filter(p=>(p[0]+p[1]+p[5]).toLowerCase().includes(q));if(f)rows=rows.filter(p=>p[4]===f);document.querySelector("#positionsTable").innerHTML=table(rows)};
  search?.addEventListener("input",apply);filter?.addEventListener("change",apply);
}
function render(){const view=(location.hash.slice(1)||"portfolio");document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.dataset.view===view));document.querySelector(".workspace-switcher strong").textContent=displayName(portfolio.name);document.querySelector('nav a[data-view="positions"] b').textContent=positions.length;app.innerHTML=view==="portfolio"?dashboard():view==="positions"?positionsView():placeholder(view);bind();document.querySelector("#sidebar").classList.remove("open")}
function openModal(){notify("Public demo uses fictional holdings. Run the local app to import a private portfolio.")}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
function openSettings(){notify("Public demo · market connections are available only in the local application.")}
function closeSettings(){settingsModal.classList.remove("open");settingsModal.setAttribute("aria-hidden","true")}
function formatDate(value){return value?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(value)):"Not reported"}
let marketConnections={fyers:{status:"not_configured"},upstox:{status:"not_connected"}};
function paintMarketStatus(){
  const button=document.querySelector("#marketDataStatusBtn"),fyers=marketConnections.fyers,upstox=marketConnections.upstox;
  const connected=fyers.status==="connected"?"FYERS":upstox.status==="connected"?"Upstox":null,expired=[fyers.status,upstox.status].includes("expired");
  button.className=`integration-status ${connected?'connected':expired?'expired':'disconnected'}`;button.querySelector("span").textContent=connected?`${connected} live`:expired?"Data session expired":"Connect data";
}
function paintUpstoxStatus(status){
  const connected=status.status==="connected",expired=status.status==="expired";
  marketConnections.upstox=status;const state=document.querySelector("#upstoxConnectionState"),disconnect=document.querySelector("#disconnectUpstox");
  state.className=`connection-state ${connected?'connected':expired?'expired':''}`;state.innerHTML=`<i></i><div><strong>${connected?'Connected · read-only':expired?'Token expired':'Not connected'}</strong><small>${connected?`Verified ${formatDate(status.verifiedAt)}${status.expiresAt?` · expires ${formatDate(status.expiresAt)}`:''}`:expired?'Generate and save a replacement Analytics Token.':'Generate a free Analytics Token, then paste it below.'}</small></div>`;
  disconnect.hidden=!connected;document.querySelector("#upstoxToken").value="";document.querySelector("#upstoxSummaryStatus").textContent=connected?"Connected":expired?"Expired":"Not connected";paintMarketStatus();
}
function paintFyersStatus(status){
  marketConnections.fyers=status;const connected=status.status==="connected",expired=status.status==="expired",configured=status.status==="needs_auth";
  const state=document.querySelector("#fyersConnectionState"),disconnect=document.querySelector("#disconnectFyers"),button=document.querySelector("#connectFyers"),secret=document.querySelector("#fyersSecretId");
  state.className=`connection-state ${connected?'connected':expired?'expired':''}`;state.innerHTML=`<i></i><div><strong>${connected?'Connected · data only':expired?'Daily session expired':configured?'App configured · sign-in required':'Not configured'}</strong><small>${connected?`Verified ${formatDate(status.verifiedAt)}${status.expiresAt?` · expires ${formatDate(status.expiresAt)}`:''}`:expired?'Sign in again to renew market-data access.':configured?'Continue through FYERS login to create the daily session.':'Create a FYERS data app and enter its credentials below.'}</small></div>`;
  document.querySelector("#fyersRedirectUri").value=status.redirectUri||"";if(status.appId)document.querySelector("#fyersAppId").value=status.appId;
  secret.required=!status.appId;secret.placeholder=status.appId?"Saved securely · leave blank to reuse":"Your app secret";disconnect.hidden=status.status==="not_configured";button.textContent=connected?"Reconnect FYERS":status.appId?"Sign in to FYERS":"Save and sign in to FYERS";paintMarketStatus();
}
async function refreshConnections(){
  const [fyers,upstox]=await Promise.all([fetch("/api/integrations/fyers").then(r=>r.json()).catch(()=>({status:"not_configured"})),fetch("/api/integrations/upstox").then(r=>r.json()).catch(()=>({status:"not_connected"}))]);paintFyersStatus(fyers);paintUpstoxStatus(upstox);
}
async function connectUpstox(event){
  event.preventDefault();const token=document.querySelector("#upstoxToken").value.trim(),button=document.querySelector("#connectUpstox");if(!token)return;
  button.disabled=true;button.textContent="Verifying…";
  try{const response=await fetch("/api/integrations/upstox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Connection failed");paintUpstoxStatus(result);notify("Upstox connected · read-only market data ready")}
  catch(error){notify(error.message)}finally{button.disabled=false;button.textContent="Verify and connect"}
}
async function disconnectUpstox(){
  if(!confirm("Disconnect Upstox and remove the locally saved token?"))return;
  const response=await fetch("/api/integrations/upstox",{method:"DELETE"});const result=await response.json();if(!response.ok)return notify(result.error||"Could not disconnect");paintUpstoxStatus(result);notify("Upstox disconnected")
}
async function connectFyers(event){
  event.preventDefault();const appId=document.querySelector("#fyersAppId").value.trim(),secretId=document.querySelector("#fyersSecretId").value.trim(),button=document.querySelector("#connectFyers");button.disabled=true;
  try{
    if(secretId||!marketConnections.fyers.appId){button.textContent="Saving…";const response=await fetch("/api/integrations/fyers/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({appId,secretId})});const result=await response.json();if(!response.ok)throw new Error(result.error||"FYERS setup failed");paintFyersStatus(result)}
    button.textContent="Opening FYERS…";location.href="/api/integrations/fyers/authorize";
  }catch(error){notify(error.message);button.disabled=false;button.textContent="Save and sign in to FYERS"}
}
async function disconnectFyers(){
  if(!confirm("Disconnect FYERS and remove its locally saved credentials?"))return;const response=await fetch("/api/integrations/fyers",{method:"DELETE"});const result=await response.json();if(!response.ok)return notify(result.error||"Could not disconnect");document.querySelector("#fyersAppId").value="";document.querySelector("#fyersSecretId").value="";paintFyersStatus(result);notify("FYERS disconnected")
}
function uiHolding(row,total){if(Array.isArray(row))return row;const weight=row.weightPct??(total&&row.marketValue?row.marketValue/total*100:0);const bucket={reduce_review:"review",exit_review:"exit",insufficient_evidence:"review"}[row.researchView?.bucket]||row.researchView?.bucket||"review";const signal=status=>["bullish","constructive"].includes(status)?"up":["bearish","weak"].includes(status)?"down":["neutral"].includes(status)?"flat":"na";return [row.ticker||"—",row.company||row.ticker||"Unknown",weight,row.unrealizedPnLPct,bucket,row.researchView?.label||"Analysis pending",[signal(row.timeframes?.monthly?.status),signal(row.timeframes?.weekly?.status),signal(row.timeframes?.daily?.status)]]}
async function loadPortfolio() {portfolio=structuredClone(demoPortfolio);positions=portfolio.positions;render()}
async function refreshPortfolioList(){document.querySelector('#portfolioSelect').innerHTML='<option value="sample">Sample portfolio · 5 holdings</option>'}
async function uploadPortfolio(){notify('Uploads are available in the local application only.')}
document.querySelector("#portfolioSelect").onchange=e=>loadPortfolio(e.target.value).then(()=>notify(`${portfolio.name} loaded`)).catch(error=>notify(error.message));document.querySelector("#uploadBtn").onclick=openModal;document.querySelector("#closeModal").onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.querySelector("#sampleBtn").onclick=()=>loadPortfolio("sample").then(()=>{closeModal();document.querySelector("#portfolioSelect").value="sample";notify("Sample portfolio loaded")});document.querySelector("#portfolioFile").onchange=async e=>{const file=e.target.files[0];if(!file)return;notify(`Saving ${file.name}…`);try{await uploadPortfolio(file)}catch(error){notify(error.message)}};document.querySelector("#menuBtn").onclick=()=>document.querySelector("#sidebar").classList.toggle("open");document.querySelector("#settingsBtn").onclick=openSettings;document.querySelector("#marketDataStatusBtn").onclick=openSettings;document.querySelector("#closeSettings").onclick=closeSettings;settingsModal.onclick=e=>{if(e.target===settingsModal)closeSettings()};document.querySelector("#fyersForm").onsubmit=connectFyers;document.querySelector("#disconnectFyers").onclick=disconnectFyers;document.querySelector("#copyFyersRedirect").onclick=async()=>{await navigator.clipboard.writeText(document.querySelector("#fyersRedirectUri").value);notify("FYERS redirect URL copied")};document.querySelector("#upstoxForm").onsubmit=connectUpstox;document.querySelector("#disconnectUpstox").onclick=disconnectUpstox;document.querySelector("#toggleToken").onclick=()=>{const input=document.querySelector("#upstoxToken");input.type=input.type==="password"?"text":"password";document.querySelector("#toggleToken").textContent=input.type==="password"?"Show":"Hide"};window.addEventListener("hashchange",render);const integrationResult=new URLSearchParams(location.search).get("integration");if(integrationResult){history.replaceState({},"",location.pathname+location.hash);setTimeout(()=>notify(integrationResult==="fyers-connected"?"FYERS connected · market data ready":"Market-data connection updated"),500)}loadPortfolio().then(()=>refreshPortfolioList()).catch(()=>render());
